### ISSUE TITLE
Application crashes when rendering blank template

### ISSUE THREAD

**Issue by icompuiz** [icompuiz/toastio#1]
Error message thrown by server

```
\toastio\server\api\content\content.controller.js:385
                                .map(function(match) {
                                 ^
TypeError: Cannot call method 'map' of null
    at findBlocks (\toastio\server\api\content\content.controller.js:385:34)
    at \toastio\server\api\content\content.controller.js:404:25
    at done (\toastio\server\components\nesting\index.js:174:17)
    at \toastio\node_modules\async\lib\async.js:729:17
    at Promise.<anonymous> (\toastio\server\components\nesting\index.js:162:21)
    at Promise.<anonymous> (\toastio\node_modules\mongoose\node_modules\mpromise\lib\pro
    at Promise.emit (events.js:95:17)
    at Promise.emit (\toastio\node_modules\mongoose\node_modules\mpromise\lib\promise.js
    at Promise.fulfill (\toastio\node_modules\mongoose\node_modules\mpromise\lib\promise
    at Promise.resolve (\toastio\node_modules\mongoose\lib\promise.js:114:23)
```

**Comment by icompuiz** [comment]
Edit: Application crashes when template has no blocks declared
