### ISSUE TITLE
Cannot call method 'where' of undefined

### ISSUE THREAD

**Issue by icompuiz** [icompuiz/toastio#2]
Error message

```
TypeError: Cannot call method 'where' of undefined
    at \toastio\server\components\nesting\index.js:518:22
    at Layer.handle [as handle_request] (\toastio\node_modules\express\lib\router\layer.
    at next (\toastio\node_modules\express\lib\router\route.js:100:13)
    at resource.after.before.before.before.checkDocumentById._id (\toastio\server\compon
    at Layer.handle [as handle_request] (\toastio\node_modules\express\lib\router\layer.
    at next (\toastio\node_modules\express\lib\router\route.js:100:13)
    at Route.dispatch (\toastio\node_modules\express\lib\router\route.js:81:3)
    at Layer.handle [as handle_request] (\toastio\node_modules\express\lib\router\layer.
    at \toastio\node_modules\express\lib\router\index.js:234:24
    at param (\toastio\node_modules\express\lib\router\index.js:331:14)
```

**Comment by icompuiz** [comment]
This happens when installing latest versions of node-restful
